-- =============================================================================
-- 0009_schema_routes.sql
-- Add bbox to mountains; add routes table; migrate canonical_trails,
-- trail_cells, trail_cell_transitions from mountain_id to route_id.
-- hiking_sessions gains a nullable route_id.
-- =============================================================================

-- ── 0. mountains bbox ────────────────────────────────────────────────────────

alter table public.mountains add column if not exists bbox text;

-- ── 1. routes table ──────────────────────────────────────────────────────────

create table public.routes (
  id           text        primary key,
  mountain_id  text        not null references public.mountains(id),
  display_name text        not null,
  created_at   timestamptz not null default now()
);

-- ── 2. Drop views that depend on the mountain_id columns we are removing ─────

drop view if exists public.operator_quality_summary;
drop view if exists public.operator_route_quality_detail;
drop view if exists public.operator_route_coverage;

-- ── 3. Seed default routes from existing canonical trail data ─────────────────
-- Creates one "Main Trail" route per mountain that already has a canonical trail.

insert into public.routes (id, mountain_id, display_name)
select distinct
  mountain_id || '-main',
  mountain_id,
  'Main Trail'
from public.canonical_trails
on conflict (id) do nothing;

-- ── 4. canonical_trails ───────────────────────────────────────────────────────

alter table public.canonical_trails
  add column route_id text references public.routes(id);

update public.canonical_trails
  set route_id = mountain_id || '-main';

alter table public.canonical_trails
  alter column route_id set not null;

-- Drop old unique constraint (name generated by PostgreSQL from column list)
do $$
declare v_name text;
begin
  select conname into v_name
  from pg_constraint c
  join pg_class t on t.oid = c.conrelid
  where t.relname = 'canonical_trails'
    and c.contype = 'u'
    and c.conname like 'canonical_trails_mountain_id%';
  if found then
    execute format('alter table public.canonical_trails drop constraint %I', v_name);
  end if;
end
$$;

alter table public.canonical_trails
  drop column mountain_id;

alter table public.canonical_trails
  add constraint canonical_trails_route_id_version_key unique (route_id, version);

-- ── 5. trail_cells ────────────────────────────────────────────────────────────

alter table public.trail_cells
  add column route_id text references public.routes(id);

update public.trail_cells
  set route_id = mountain_id || '-main';

alter table public.trail_cells
  alter column route_id set not null;

do $$
declare v_name text;
begin
  select conname into v_name
  from pg_constraint c
  join pg_class t on t.oid = c.conrelid
  where t.relname = 'trail_cells'
    and c.contype = 'u'
    and c.conname like 'trail_cells_mountain_id%';
  if found then
    execute format('alter table public.trail_cells drop constraint %I', v_name);
  end if;
end
$$;

alter table public.trail_cells
  drop column mountain_id;

alter table public.trail_cells
  add constraint trail_cells_route_id_cell_key_key unique (route_id, cell_key);

-- ── 6. trail_cell_transitions ─────────────────────────────────────────────────

alter table public.trail_cell_transitions
  add column route_id text references public.routes(id);

update public.trail_cell_transitions
  set route_id = mountain_id || '-main';

alter table public.trail_cell_transitions
  alter column route_id set not null;

do $$
declare v_name text;
begin
  select conname into v_name
  from pg_constraint c
  join pg_class t on t.oid = c.conrelid
  where t.relname = 'trail_cell_transitions'
    and c.contype = 'u'
    and c.conname like 'trail_cell_transitions_mountain_id%';
  if found then
    execute format('alter table public.trail_cell_transitions drop constraint %I', v_name);
  end if;
end
$$;

alter table public.trail_cell_transitions
  drop column mountain_id;

alter table public.trail_cell_transitions
  add constraint trail_cell_transitions_route_id_from_to_key
    unique (route_id, from_cell_key, to_cell_key);

-- ── 7. hiking_sessions: optional route association ────────────────────────────

alter table public.hiking_sessions
  add column route_id text references public.routes(id);

-- ── 8. RLS ────────────────────────────────────────────────────────────────────

alter table public.routes enable row level security;

create policy "Users can read route catalog"
  on public.routes
  for select
  using (true);
